import { containsAny, jaccardSimilarity, normalizeText } from "../../lib/strings.js";
import type { MatchDecision, MatchResult, SearchCandidate } from "../../types.js";

const NEGATIVE_MARKERS = [
  "live",
  "cover",
  "karaoke",
  "reaction",
  "sped up",
  "slowed",
  "reverb",
  "8d",
  "nightcore",
  "remix",
  "lyrics",
  "lyric",
  "fanmade",
  "fan made",
  "instrumental",
];

const OFFICIAL_MARKERS = [
  "official audio",
  "official video",
  "provided to youtube",
  "topic",
  "vevo",
  "auto-generated by youtube",
];

export interface TrackForMatching {
  spotifyTrackId: string;
  trackName: string;
  artistNames: string[];
  albumName: string | null;
  durationMs: number;
}

export function rankCandidates(
  track: TrackForMatching,
  candidates: SearchCandidate[],
) {
  return candidates
    .map((candidate) => scoreCandidate(track, candidate))
    .sort((left, right) => right.score - left.score);
}

export function classifyMatch(
  track: TrackForMatching,
  candidates: SearchCandidate[],
  threshold: number,
): MatchDecision {
  const all = rankCandidates(track, candidates);
  const best = all[0] ?? null;

  if (!best) {
    return {
      disposition: "no_match",
      best: null,
      all,
    };
  }

  if (best.score >= threshold) {
    return {
      disposition: "matched_auto",
      best,
      all,
    };
  }

  return {
    best,
    all,
    disposition: "review_required",
  };
}

export function scoreCandidate(track: TrackForMatching, candidate: SearchCandidate): MatchResult {
  const reasons: string[] = [];
  let score = 0;

  const normalizedTrackName = normalizeText(track.trackName);
  const normalizedArtists = track.artistNames.map((artist) => normalizeText(artist));
  const normalizedAlbum = normalizeText(track.albumName ?? "");
  const normalizedTitle = normalizeText(candidate.title);
  const normalizedChannel = normalizeText(candidate.channelTitle);
  const combinedText = `${normalizedTitle} ${normalizedChannel}`;

  const titleSimilarity = jaccardSimilarity(track.trackName, candidate.title);
  score += titleSimilarity * 40;
  reasons.push(`title:${titleSimilarity.toFixed(2)}`);

  if (normalizedTitle.includes(normalizedTrackName)) {
    score += 15;
    reasons.push("contains track title");
  }

  const artistHits = normalizedArtists.filter((artist) => combinedText.includes(artist)).length;
  if (artistHits > 0) {
    score += Math.min(artistHits * 12, 24);
    reasons.push(`artist hits:${artistHits}`);
  }

  const channelSimilarity = Math.max(
    0,
    ...normalizedArtists.map((artist) => jaccardSimilarity(artist, candidate.channelTitle)),
  );
  score += channelSimilarity * 15;

  if (normalizedAlbum && normalizedTitle.includes(normalizedAlbum)) {
    score += 5;
    reasons.push("contains album");
  }

  if (containsAny(`${candidate.title} ${candidate.channelTitle}`, OFFICIAL_MARKERS)) {
    score += 20;
    reasons.push("official marker");
  }

  if (normalizedChannel.includes("topic")) {
    score += 12;
    reasons.push("topic channel");
  }

  if (normalizedChannel.includes("vevo")) {
    score += 10;
    reasons.push("vevo channel");
  }

  if (candidate.durationSeconds) {
    const differenceSeconds = Math.abs(track.durationMs / 1000 - candidate.durationSeconds);
    if (differenceSeconds <= 5) {
      score += 15;
      reasons.push("duration <=5s");
    } else if (differenceSeconds <= 15) {
      score += 10;
      reasons.push("duration <=15s");
    } else if (differenceSeconds <= 30) {
      score += 5;
      reasons.push("duration <=30s");
    } else if (differenceSeconds > 90) {
      score -= 20;
      reasons.push("duration mismatch");
    }
  }

  if (candidate.isEmbeddable === false) {
    score -= 25;
    reasons.push("not embeddable");
  }

  if (candidate.isSyndicated === false) {
    score -= 10;
    reasons.push("not syndicated");
  }

  if (containsAny(candidate.title, NEGATIVE_MARKERS)) {
    score -= 35;
    reasons.push("negative title marker");
  }

  if (containsAny(candidate.channelTitle, ["cover", "karaoke", "fan"])) {
    score -= 15;
    reasons.push("negative channel marker");
  }

  return {
    candidate,
    score: Math.max(0, Math.min(100, score)),
    reasons,
  };
}
